### ISSUE TITLE
a question about the dataset

### ISSUE THREAD

**Issue by CocoGzh** [welch-lab/PerturbNet#1]
The dataset in example folder (https://www.dropbox.com/sh/cl8e4dm6a5peyoi/AAC2Oj200ii34k77Q0XGD2Nia?dl=0) has been deleted. Could you upload a toy dataset in anywhere else? Thx!

**Comment by hengshiyu** [comment]
Thanks for your question. We have updated the example data folder at: https://www.dropbox.com/sh/3nk6qk1653h2y1v/AACplqpkgt3LH9_JDrsk-Hg4a?dl=0. Hope it will be helpful!

**Comment by Naghipourfar** [comment]
Hi, 

Thanks for providing the Sciplex example. Can you also please provide an example for the genetic interactions application?

**Comment by hengshiyu** [comment]
> Hi,
> 
> Thanks for providing the Sciplex example. Can you also please provide an example for the genetic interactions application?

Thanks. We have updated the GitHub page on [`./examples`](https://github.com/welch-lab/PerturbNet/tree/main/examples) page with the genetic interaction data application.
