### ISSUE TITLE
GI Application example 

### ISSUE THREAD

**Issue by Naghipourfar** [welch-lab/PerturbNet#3]
Hi, 

Thanks for providing the Sciplex example. Can you also please provide an example for the genetic interactions application?

_Originally posted by @Naghipourfar in https://github.com/welch-lab/PerturbNet/issues/1#issuecomment-1384764306_

**Comment by hengshiyu** [comment]
> Hi,
> 
> Thanks for providing the Sciplex example. Can you also please provide an example for the genetic interactions application?
> 
> _Originally posted by @Naghipourfar in [#1 (comment)](https://github.com/welch-lab/PerturbNet/issues/1#issuecomment-1384764306)_

Thanks. We have updated the GitHub page on [`./examples`](https://github.com/welch-lab/PerturbNet/tree/main/examples) page with the genetic interaction data application.

**Comment by zoepiran** [comment]
Hi, 
Following on this, is it possible to provide details of training for all models used in the sci-plex setting (e.g. the steps taken to create the pre-trained models) either code or a brief explanation.
Thank you in advance :)
